version: 2

project_name: cb-rs

builds:
  - id: cb
    builder: rust
    command: zigbuild
    binary: cb
    targets:
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl
      - aarch64-apple-darwin

archives:
  - id: cb
    ids: [cb]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "linux" }}Linux
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - formats: ["tar.zst"]
    files:
      - src: share/man/*
        dst: man
      - src: share/completions/*
        dst: completions

nfpms:
  - id: cb
    package_name: cb-rs
    ids: [cb]
    formats:
      - deb
      - rpm
    maintainer: Michael Adler <therisen06@gmail.com>
    homepage: https://github.com/michaeladler/cb-rs
    description: faster, safer Rust rewrite of the file copy/cut/paste core of cb
    section: utils
    priority: optional
    contents:
      - src: share/man/cb.1
        dst: man1/cb.1
      - src: share/completions/cb.bash
        dst: bash-completion/completions/cb
        type: config
      - src: share/completions/_cb
        dst: zsh/site-functions/_cb
        type: config
      - src: share/completions/cb.fish
        dst: fish/vendor_completions.d/cb.fish
        type: config

checksum:
  name_template: "checksums.txt"

release:
  draft: true
  replace_existing_draft: true

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
